// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Kplrk7dMCDCjkwSldquRDsTeAfefIVQ',
    appId: '1:137488487050:web:c799a7d920ace1cfca9373',
    messagingSenderId: '137488487050',
    projectId: 'flexride-a96ad',
    authDomain: 'flexride-a96ad.firebaseapp.com',
    storageBucket: 'flexride-a96ad.appspot.com',
    measurementId: 'G-T1VDWMWK11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDctDFeWm0Sn3ZjnxfYbPy5TboNiyVdyko',
    appId: '1:137488487050:android:3459a818a977ec95ca9373',
    messagingSenderId: '137488487050',
    projectId: 'flexride-a96ad',
    storageBucket: 'flexride-a96ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTPeoMaXE0NA4G6-07jUmHs-xMbdC_g_8',
    appId: '1:137488487050:ios:43aad2f1ca64a3f9ca9373',
    messagingSenderId: '137488487050',
    projectId: 'flexride-a96ad',
    storageBucket: 'flexride-a96ad.appspot.com',
    iosBundleId: 'com.domain.flexride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTPeoMaXE0NA4G6-07jUmHs-xMbdC_g_8',
    appId: '1:137488487050:ios:43aad2f1ca64a3f9ca9373',
    messagingSenderId: '137488487050',
    projectId: 'flexride-a96ad',
    storageBucket: 'flexride-a96ad.appspot.com',
    iosBundleId: 'com.domain.flexride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_Kplrk7dMCDCjkwSldquRDsTeAfefIVQ',
    appId: '1:137488487050:web:845f68c1e47c256bca9373',
    messagingSenderId: '137488487050',
    projectId: 'flexride-a96ad',
    authDomain: 'flexride-a96ad.firebaseapp.com',
    storageBucket: 'flexride-a96ad.appspot.com',
    measurementId: 'G-5LEYWECJJJ',
  );
}
